"""empty message

Revision ID: 9a15871c3e18
Revises: 2c3e1f9e0fc9
Create Date: 2017-09-10 16:34:28.886377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a15871c3e18'
down_revision = '2c3e1f9e0fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.drop_column('category', 'post_id')
    op.add_column('post', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'category_id')
    op.add_column('category', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('category_ibfk_1', 'category', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
